# Generated by Django 5.0.4 on 2024-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('name', models.TextField()),
                ('father_name', models.TextField()),
                ('stnd', models.IntegerField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('number', models.TextField()),
            ],
        ),
    ]
